FROM rabbitmq

LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"

#RUN rabbitmq-plugins enable --offline rabbitmq_management
#RUN rabbitmq-plugins enable rabbitmq_mqtt
#RUN rabbitmq-plugins enable rabbitmq_web_mqtt

#RUN rabbitmqctl add_user mqtt-test mqtt-test
#RUN rabbitmqctl set_permissions -p / mqtt-test ".*" ".*" ".*"
#RUN rabbitmqctl set_user_tags mqtt-test management

EXPOSE 15671 15672
